/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cleanarchitecture.adapter;

import br.com.ecftef.ViewECFTEF;
import javax.swing.*;
import java.net.URL;
/**
 *
 * @author Pedro Henrique
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private HelpSet hs;
    private HelpBroker hb;
    private URL hsURL;
    private MenuModel menuModel;
    private MenuUseCase menuUseCase;

    public MenuView() {
        initComponents();
        menuModel = new MenuModel(/* Inicialize com seu EntityManager */);
        menuUseCase = new MenuUseCase();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
        String[] args = {"Cadastro De Produtos"};
        if (menuModel.verificaAcesso("Cadastro De Produtos", jLabel2.getText())) {
            menuUseCase.abrirProdutos(args);
        } else {
            JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
        }
    }

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {
        String[] args = {"Movimento - Orçamento de Venda"};
        if (menuModel.verificaAcesso("Movimento - Orçamento de Venda", jLabel2.getText())) {
            menuUseCase.abrirMovimentoOrcamentoVenda(args);
        } else {
            JOptionPane.showMessageDialog(null, "Você não possui acesso ao módulo!");
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
        menuUseCase.abrirViewECFTEF(/* Argumentos necessários */);
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            Runtime.getRuntime().exec("calc.exe");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao executar a calculadora.");
        }
    }

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {
        openHelp();
    }
}
